services:
  # Backend
  - type: web
    name: code-connect-backend
    runtime: docker
    dockerContext: backend
    dockerfilePath: Dockerfile

  # Frontend
  - type: web
    name: code-connect-frontend
    runtime: docker
    dockerContext: frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: VITE_SERVER_URL
        fromService:
          type: web
          name: code-connect-backend
          property: host
